<a href="https://colab.research.google.com/github/thefuriouspanda/AB-De-Villiers-vs-Jasprit-Bumrah/blob/main/notebooks/Getting_started_with_google_colab_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IPL POINT AUTOMATION

In [1]:
import requests
from bs4 import BeautifulSoup

url = "https://crex.com/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

links = soup.find_all("a", href=True)

match_links = []

for link in links:
    if "/scoreboard/" in link["href"]:
        match_links.append("https://crex.com" + link["href"])

print(match_links[:5])
match_links = list(set(match_links))
print(match_links)

['https://crex.com/scoreboard/10BK/2AR/2nd-ODI/U/W/ban-vs-pak-2nd-odi-pakistan-tour-of-bangladesh-2026/live', 'https://crex.com/scoreboard/10OP/2EX/13th-Match/SW/62/fais-vs-psw-13th-match-pakistan-national-t20-2026/live', 'https://crex.com/scoreboard/10OQ/2EX/14th-Match/TP/61/bhwr-vs-lahw-14th-match-pakistan-national-t20-2026/info', 'https://crex.com/scoreboard/10OO/2EX/12th-Match/68/TG/karb-vs-mul-12th-match-pakistan-national-t20-2026/scorecard', 'https://crex.com/scoreboard/10SP/2F1/3rd-Match/YO/MC/icn-vs-kso-3rd-match-legends-league-cricket-2026/live']
['https://crex.com/scoreboard/10TK/2F6/12th-Match/1F2/1EZ/br-vs-gt-12th-match-thunderbolt-t10-league-2026/scorecard', 'https://crex.com/scoreboard/W5R/1X9/39th-Match/O0/NV/act-w-vs-wa-w-39th-match-womens-national-cricket-league-2025-26/scorecard', 'https://crex.com/scoreboard/10J0/2ER/14th-Match/JG/J7/rocks-vs-wp-14th-match-csa-provincial-one-day-challenge-division-one-2026/scorecard', 'https://crex.com/scoreboard/10K4/2ES/24th-Match/JD/JC/eci-vs-lmp-24th-match-csa-provincial-one-day-challenge-division-two-2026/scorecard', 'https://crex.com/scoreboard/10K6/2ES/26th-Match/JF/16R/es-vs-sa-e-26th-match-csa-provincial-one-day-challenge-division-two-2026/info', 'https://crex.com/scoreboard/10BK/2AR/2nd-ODI/U/W/ban-vs-pak-2nd-odi-pakistan-tour-of-bangladesh-2026/live', 'https://crex.com/scoreboard/10RJ/2F3/7th-Match/TB/WO/caym-vs-mex-7th-match-mens-t20-wc-americas-sub-regional-qualifier-b-2026/scorecard', 'https://crex.com/scoreboard/10OO/2EX/12th-Match/68/TG/karb-vs-mul-12th-match-pakistan-national-t20-2026/scorecard', 'https://crex.com/scoreboard/10TN/2F6/15th-Match/1F4/1EY/dc-vs-re-15th-match-thunderbolt-t10-league-2026/info', 'https://crex.com/scoreboard/10J4/2ER/18th-Match/6A/JE/dol-vs-nwd-18th-match-csa-provincial-one-day-challenge-division-one-2026/info', 'https://crex.com/scoreboard/10SP/2F1/3rd-Match/YO/MC/icn-vs-kso-3rd-match-legends-league-cricket-2026/live', 'https://crex.com/scoreboard/10TI/2F6/10th-Match/1EY/1F2/br-vs-re-10th-match-thunderbolt-t10-league-2026/scorecard', 'https://crex.com/scoreboard/10W0/2F5/7th-Match/1EV/1F6/ht-vs-ysk-7th-match-ayodhya-premier-league-2026/info', 'https://crex.com/scoreboard/10XX/2FB/2nd-ODI/HP/PM/brn-vs-mas-2nd-odi-bahrain-tour-of-malaysia-2026/info', 'https://crex.com/scoreboard/10J3/2ER/17th-Match/JG/6C/rocks-vs-war-17th-match-csa-provincial-one-day-challenge-division-one-2026/info', 'https://crex.com/scoreboard/10VZ/2F5/6th-Match/1ES/1EU/gt-vs-ss-6th-match-ayodhya-premier-league-2026/info', 'https://crex.com/scoreboard/W5P/1X9/37th-Match/3N/NX/qf-w-vs-vic-w-37th-match-womens-national-cricket-league-2025-26/scorecard', 'https://crex.com/scoreboard/10U7/2F9/4th-T20/IM/1F7/bot-vs-les-4th-t20-lesotho-tour-of-botswana-2026/scorecard', 'https://crex.com/scoreboard/10R9/2F2/11th-Match/1F8/1EN/cde-vs-mhkl-11th-match-tillo-t20-cup-2026/scorecard', 'https://crex.com/scoreboard/10TM/2F6/14th-Match/1EZ/1F3/gt-vs-mm-14th-match-thunderbolt-t10-league-2026/info', 'https://crex.com/scoreboard/10VY/2F5/5th-Match/1ET/1EW/bb-vs-cc-5th-match-ayodhya-premier-league-2026/scorecard', 'https://crex.com/scoreboard/10RA/2F2/1st-Semi-Final/1EQ/1EM/neh-vs-nod-1st-semi-final-tillo-t20-cup-2026/scorecard', 'https://crex.com/scoreboard/10VX/2F5/4th-Match/1F6/1ER/gw-vs-ht-4th-match-ayodhya-premier-league-2026/scorecard', 'https://crex.com/scoreboard/10TL/2F6/13th-Match/1EX/1EY/pl-vs-re-13th-match-thunderbolt-t10-league-2026/info', 'https://crex.com/scoreboard/10TJ/2F6/11th-Match/1EX/1F3/mm-vs-pl-11th-match-thunderbolt-t10-league-2026/scorecard', 'https://crex.com/scoreboard/10K5/2ES/25th-Match/6E/JA/kng-vs-rno-25th-match-csa-provincial-one-day-challenge-division-two-2026/info', 'https://crex.com/scoreboard/10RL/2F3/9th-Match/135/WO/arg-vs-mex-9th-match-mens-t20-wc-americas-sub-regional-qualifier-b-2026/info', 'https://crex.com/scoreboard/10SO/2F1/2nd-Match/M9/MA/ing-vs-rrp-2nd-match-legends-league-cricket-2026/scorecard', 'https://crex.com/scoreboard/10OP/2EX/13th-Match/SW/62/fais-vs-psw-13th-match-pakistan-national-t20-2026/live', 'https://crex.com/scoreboard/10OQ/2EX/14th-Match/TP/61/bhwr-vs-lahw-14th-match-pakistan-national-t20-2026/info']

In [2]:
match_url = None

for link in match_links:
    if "ban-vs-pak" in link.lower():
        match_url = link
        break

if match_url:
    scorecard_link = match_url.replace("/live", "/scorecard")
    print(scorecard_link)
else:
    print("Match not found")

https://crex.com/scoreboard/10BK/2AR/2nd-ODI/U/W/ban-vs-pak-2nd-odi-pakistan-tour-of-bangladesh-2026/scorecard

In [3]:
response = requests.get(match_url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

print(soup.title.text)

BAN 27-3 (6.3) (Litton Das 13(15), Towhid Hridoy 0(3)) vs Pakistan 274-10 ((47.3)) 2nd ODI live | Pakistan tour of bangladesh 2026 - CREX

In [4]:
# Step 4 → scrape scorecard
response = requests.get(scorecard_link, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

In [5]:
tables = soup.find_all("table")

print("Total tables found:", len(tables))

Total tables found: 3

In [6]:
for i, table in enumerate(tables):
    print("\n================")
    print("Table Index:", i)
    print("================")
    print(table.text[:800])

================
Table Index: 0
================
BatterRB4s6sSRSaif Hassan c Samad b Jnr 121220100.00Tanzid Hasan c Jnr b Afridi 170014.29Najmul Hossain Shanto b Afridi  02000.00Litton Das(WK) Batting 13152086.67Towhid Hridoy Batting 03000.00

================
Table Index: 1
================
BowlerOMRWERShaheen Afridi(C)3.30922.57Mohammad Wasim Jnr3.001816.00

================
Table Index: 2
================
BatsmanScoreOversTanzid Hasan13-13.0Saif Hassan13-23.1Najmul Hossain Shanto15-34.3

In [7]:
import pandas as pd

batting_rows = tables[0].find_all("tr")

batting_data = []

for row in batting_rows[1:]:
    cols = [c.text.strip() for c in row.find_all("td")]
    if len(cols) > 0:
        batting_data.append(cols)

batting_df = pd.DataFrame(batting_data)

batting_df.head()

                                0   1   2  3  4       5
0       Saif Hassan c Samad b Jnr  12  12  2  0  100.00
1     Tanzid Hasan c Jnr b Afridi   1   7  0  0   14.29
2  Najmul Hossain Shanto b Afridi   0   2  0  0    0.00
3          Litton Das(WK) Batting  13  15  2  0   86.67
4           Towhid Hridoy Batting   0   3  0  0    0.00

In [8]:
batting_df.columns = [
    "player",
    "runs",
    "balls",
    "fours",
    "sixes",
    "sr"
]

batting_df

                           player runs balls fours sixes      sr
0       Saif Hassan c Samad b Jnr   12    12     2     0  100.00
1     Tanzid Hasan c Jnr b Afridi    1     7     0     0   14.29
2  Najmul Hossain Shanto b Afridi    0     2     0     0    0.00
3          Litton Das(WK) Batting   13    15     2     0   86.67
4           Towhid Hridoy Batting    0     3     0     0    0.00

In [9]:
batting_df["runs"] = pd.to_numeric(batting_df["runs"], errors="coerce")
batting_df["balls"] = pd.to_numeric(batting_df["balls"], errors="coerce")
batting_df["fours"] = pd.to_numeric(batting_df["fours"], errors="coerce")
batting_df["sixes"] = pd.to_numeric(batting_df["sixes"], errors="coerce")
batting_df["sr"] = pd.to_numeric(batting_df["sr"], errors="coerce")

batting_df

                           player  runs  balls  fours  sixes      sr
0       Saif Hassan c Samad b Jnr    12     12      2      0  100.00
1     Tanzid Hasan c Jnr b Afridi     1      7      0      0   14.29
2  Najmul Hossain Shanto b Afridi     0      2      0      0    0.00
3          Litton Das(WK) Batting    13     15      2      0   86.67
4           Towhid Hridoy Batting     0      3      0      0    0.00

In [10]:
import numpy as np

# Playing XI
batting_df["playing_xi_points"] = 4

# Base run points
batting_df["run_points"] = batting_df["runs"]

# Boundary bonus (updated rule)
batting_df["boundary_points"] = (
    batting_df["fours"] * 4
    + batting_df["sixes"] * 6
)

# Milestone bonus
batting_df["milestone_points"] = np.select(
    [
        batting_df["runs"] >= 100,
        batting_df["runs"] >= 75,
        batting_df["runs"] >= 50,
        batting_df["runs"] >= 30
    ],
    [
        16,
        12,
        8,
        4
    ],
    default=0
)

# Not-out detection logic (UPDATED)
batting_df["not_out"] = batting_df["player"].str.lower().str.contains(
    "not out|batting",
    regex=True
)

# Duck penalty (only if OUT)
batting_df["duck_penalty"] = np.where(
    (batting_df["runs"] == 0) &
    (batting_df["balls"] > 0) &
    (batting_df["not_out"] == False),
    -2,
    0
)

# Strike rate numeric
batting_df["sr"] = pd.to_numeric(batting_df["sr"], errors="coerce")

# Strike rate bonus (balls >=10 only)
batting_df["sr_points"] = np.select(
    [
        (batting_df["balls"] >= 10) & (batting_df["sr"] >= 200),
        (batting_df["balls"] >= 10) & (batting_df["sr"] >= 170),
        (batting_df["balls"] >= 10) & (batting_df["sr"] >= 150),
        (batting_df["balls"] >= 10) & (batting_df["sr"] >= 130),
        (batting_df["balls"] >= 10) & (batting_df["sr"] < 50),
        (batting_df["balls"] >= 10) & (batting_df["sr"] < 60),
        (batting_df["balls"] >= 10) & (batting_df["sr"] < 70)
    ],
    [
        8,
        6,
        4,
        2,
        -6,
        -4,
        -2
    ],
    default=0
)

# Final batting fantasy points
batting_df["batting_points"] = (
    batting_df["playing_xi_points"]
    + batting_df["run_points"]
    + batting_df["boundary_points"]
    + batting_df["milestone_points"]
    + batting_df["sr_points"]
    + batting_df["duck_penalty"]
)

batting_df.sort_values("batting_points", ascending=False)

,player,runs,balls,fours,sixes,sr,playing_xi_points,run_points,boundary_points,milestone_points,not_out,duck_penalty,sr_points,batting_points
3,Litton Das(WK) Batting,13,15,2,0,86.67,4,13,8,0,True,0,0,25
0,Saif Hassan c Samad b Jnr,12,12,2,0,100.00,4,12,8,0,False,0,0,24
1,Tanzid Hasan c Jnr b Afridi,1,7,0,0,14.29,4,1,0,0,False,0,0,5
4,Towhid Hridoy Batting,0,3,0,0,0.00,4,0,0,0,True,0,0,4
2,Najmul Hossain Shanto b Afridi,0,2,0,0,0.00,4,0,0,0,False,-2,0,2

In [11]:
bowling_rows = tables[1].find_all("tr")

bowling_data = []

for row in bowling_rows[1:]:
    cols = [c.text.strip() for c in row.find_all("td")]
    if len(cols) > 0:
        bowling_data.append(cols)

import pandas as pd
bowling_df = pd.DataFrame(bowling_data)

bowling_df.head()

                    0    1  2   3  4     5
0   Shaheen Afridi(C)  3.3  0   9  2  2.57
1  Mohammad Wasim Jnr  3.0  0  18  1  6.00

In [12]:
bowling_df.columns = [
    "player",
    "overs",
    "maidens",
    "runs_conceded",
    "wickets",
    "econ"
]

bowling_df["overs"] = pd.to_numeric(bowling_df["overs"], errors="coerce")
bowling_df["maidens"] = pd.to_numeric(bowling_df["maidens"], errors="coerce")
bowling_df["runs_conceded"] = pd.to_numeric(bowling_df["runs_conceded"], errors="coerce")
bowling_df["wickets"] = pd.to_numeric(bowling_df["wickets"], errors="coerce")
bowling_df["econ"] = pd.to_numeric(bowling_df["econ"], errors="coerce")

bowling_df

               player  overs  maidens  runs_conceded  wickets  econ
0   Shaheen Afridi(C)    3.3        0              9        2  2.57
1  Mohammad Wasim Jnr    3.0        0             18        1  6.00

In [13]:
import re

lbw_bowled_bonus = {}
fielder_events = {}

for idx, row in batting_df.iterrows():

    text = row["player"].lower()

    # ---------- RUN OUT ----------
    if "Run out" in text:
        match = re.search(r"run out\s*\((.*?)\)", text)
        if match:
            fielder = match.group(1).strip()
            last = fielder.split()[-1]
            fielder_events[last] = fielder_events.get(last, 0) + 1.5

        continue

    # ---------- STUMP ----------
    if " st " in text:
        # st rahim b miraz
        parts = text.split("st ")[-1]
        fielder = parts.split(" b ")[0].strip()
        bowler = parts.split(" b ")[-1].strip()

        fielder_last = fielder.split()[-1]
        bowler_last = bowler.split()[-1]

        fielder_events[fielder_last] = fielder_events.get(fielder_last, 0) + 1.5
        lbw_bowled_bonus[bowler_last] = lbw_bowled_bonus.get(bowler_last, 0)

        continue

    # ---------- CAUGHT ----------
    if " c " in text:
        # c das b miraz
        parts = text.split(" c ")[-1]
        fielder = parts.split(" b ")[0].strip()
        bowler = parts.split(" b ")[-1].strip()

        fielder_last = fielder.split()[-1]
        bowler_last = bowler.split()[-1]

        fielder_events[fielder_last] = fielder_events.get(fielder_last, 0) + 1
        lbw_bowled_bonus[bowler_last] = lbw_bowled_bonus.get(bowler_last, 0)

        continue

    # ---------- LBW ----------
    if "lbw" in text:
        bowler = text.split("lbw")[-1].strip()
        bowler_last = bowler.split()[-1]

        lbw_bowled_bonus[bowler_last] = lbw_bowled_bonus.get(bowler_last, 0) + 1
        continue

    # ---------- BOWLED ONLY ----------
    # pattern: batsman b miraz
    if re.search(r"\sb\s", text):
        # ensure no catch/stump already handled
        if " c " not in text and "st " not in text:
            bowler = text.split(" b ")[-1].strip()
            bowler_last = bowler.split()[-1]

            lbw_bowled_bonus[bowler_last] = lbw_bowled_bonus.get(bowler_last, 0) + 1

In [14]:
import numpy as np

# Playing XI
bowling_df["playing_xi_points"] = 4

# Wicket points (UPDATED)
bowling_df["wicket_points"] = bowling_df["wickets"] * 30

# Maiden bonus
bowling_df["maiden_points"] = bowling_df["maidens"] * 12

bowling_df["lbw_bowled_bonus"] = bowling_df["player"].str.lower().apply(
    lambda x: lbw_bowled_bonus.get(x.split()[-1], 0)
)

bowling_df["lbw_bowled_points"] = bowling_df["lbw_bowled_bonus"] * 8

# Wicket haul bonus
bowling_df["haul_bonus"] = np.select(
    [
        bowling_df["wickets"] >= 5,
        bowling_df["wickets"] >= 4,
        bowling_df["wickets"] >= 3
    ],
    [
        16,
        8,
        4
    ],
    default=0
)

# Economy bonus (min 2 overs)
bowling_df["econ_points"] = np.select(
    [
        (bowling_df["overs"] >= 2) & (bowling_df["econ"] < 5),
        (bowling_df["overs"] >= 2) & (bowling_df["econ"] < 6),
        (bowling_df["overs"] >= 2) & (bowling_df["econ"] < 7),
        (bowling_df["overs"] >= 2) & (bowling_df["econ"] >= 12),
        (bowling_df["overs"] >= 2) & (bowling_df["econ"] >= 11),
        (bowling_df["overs"] >= 2) & (bowling_df["econ"] >= 10)
    ],
    [
        6,
        4,
        2,
        -6,
        -4,
        -2
    ],
    default=0
)

# Total bowling points
bowling_df["bowling_points"] = (
    bowling_df["playing_xi_points"]
    + bowling_df["wicket_points"]
    + bowling_df["maiden_points"]
    + bowling_df["lbw_bowled_bonus"]
    + bowling_df["haul_bonus"]
    + bowling_df["econ_points"]
)

bowling_df.sort_values("bowling_points", ascending=False)

,player,overs,maidens,runs_conceded,wickets,econ,playing_xi_points,wicket_points,maiden_points,lbw_bowled_bonus,lbw_bowled_points,haul_bonus,econ_points,bowling_points
0,Shaheen Afridi(C),3.3,0,9,2,2.57,4,60,0,0,0,0,6,70
1,Mohammad Wasim Jnr,3.0,0,18,1,6.00,4,30,0,0,0,0,2,36

In [16]:
import pandas as pd
import re

fielding_events = []

In [19]:
import re

fielding_events = []

for idx, row in batting_df.iterrows():

    text = row["player"]

    lower_text = text.lower()

    # -------- RUN OUT --------
    if "Run out" in lower_text:

        match = re.search(r"run out\s*\((.*?)\)", text, re.IGNORECASE)

        if match:
            fielder_text = match.group(1).strip()

            # multiple fielders
            if "/" in fielder_text:
                fielders = [f.strip() for f in fielder_text.split("/")]

                for f in fielders:
                    fielding_events.append({
                        "fielder_name": f,
                        "event": "runout_shared"
                    })

            else:
                fielding_events.append({
                    "fielder_name": fielder_text,
                    "event": "runout_direct"
                })

        continue

    # -------- STUMP --------
    if " st " in lower_text:

        match = re.search(r"st\s+(.*?)\s+b", text, re.IGNORECASE)

        if match:
            fielder = match.group(1).strip()

            fielding_events.append({
                "fielder_name": fielder,
                "event": "stump"
            })

        continue

    # -------- CATCH --------
    if " c " in lower_text:

        match = re.search(r"c\s+(.*?)\s+b", text, re.IGNORECASE)

        if match:
            fielder = match.group(1).strip()

            fielding_events.append({
                "fielder_name": fielder,
                "event": "catch"
            })

        continue

In [20]:
fielding_df = pd.DataFrame(fielding_events)

fielding_df

  fielder_name  event
0        Samad  catch
1          Jnr  catch

In [21]:
fielding_points = (
    fielding_df
    .groupby(["fielder_name", "event"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

import numpy as np

fielding_points["catch_points"] = fielding_points.get("catch", 0) * 8
fielding_points["stump_points"] = fielding_points.get("stump", 0) * 12

fielding_points["runout_points"] = (
    fielding_points.get("runout_direct", 0) * 12
    + fielding_points.get("runout_shared", 0) * 6
)

fielding_points["catch_bonus"] = np.select(
    [
        fielding_points.get("catch", 0) >= 4,
        fielding_points.get("catch", 0) >= 3
    ],
    [
        8,
        4
    ],
    default=0
)

fielding_points["total_fielding_points"] = (
    fielding_points["catch_points"]
    + fielding_points["stump_points"]
    + fielding_points["runout_points"]
    + fielding_points["catch_bonus"]
)

fielding_points

event,fielder_name,catch,catch_points,stump_points,runout_points,catch_bonus,total_fielding_points
0,Jnr,1,8,0,0,0,8
1,Samad,1,8,0,0,0,8

In [22]:
batting_df["clean_player"] = (
    batting_df["player"]
    .str.replace(r"(c .*|st .*|lbw .*|b .*|run out.*|batting|not out)", "", regex=True)
    .str.strip()
)

batting_df["player_key"] = (
    batting_df["clean_player"]
    .str.lower()
    .str.split()
    .str[-1]
)

batting_df[["player", "clean_player", "player_key"]]

                           player            clean_player player_key
0       Saif Hassan c Samad b Jnr             Saif Hassan     hassan
1     Tanzid Hasan c Jnr b Afridi            Tanzid Hasan      hasan
2  Najmul Hossain Shanto b Afridi   Najmul Hossain Shanto     shanto
3          Litton Das(WK) Batting  Litton Das(WK) Batting    batting
4           Towhid Hridoy Batting   Towhid Hridoy Batting    batting

In [23]:
bowling_df["player_key"] = (
    bowling_df["player"]
    .str.lower()
    .str.split()
    .str[-1]
)

bowling_df[["player", "player_key"]]

               player player_key
0   Shaheen Afridi(C)  afridi(c)
1  Mohammad Wasim Jnr        jnr

In [24]:
fielding_points["player_key"] = (
    fielding_points["fielder_name"]
    .str.lower()
    .str.split()
    .str[-1]
)

fielding_points[["fielder_name", "player_key"]]

event fielder_name player_key
0              Jnr        jnr
1            Samad      samad